DELETE http://localhost:8080/events/2
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InZpdmFhbjEyQGdtYWlsLmNvbSIsImV4cCI6MTc1NTUyNjkyNSwidXNlcklEIjoyfQ.APMX4kumeQVKPMmbn7FFQaKHf_WOIbnf-wyJiiikRU0